# Generated by Django 2.1 on 2018-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('keyphrase', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('keyphrase2', models.CharField(max_length=255)),
            ],
            options={
                'managed': False,
                'db_table': 'hierarchies',
            },
        ),
        migrations.CreateModel(
            name='Knowledge',
            fields=[
                ('keyphrase', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('content', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'knowledges',
            },
        ),
        migrations.CreateModel(
            name='Kset',
            fields=[
                ('keyphrase', models.CharField(db_column='keyphrase', max_length=255, primary_key=True, serialize=False)),
                ('name', models.TextField(db_column='name')),
                ('is_index', models.BooleanField()),
            ],
            options={
                'managed': False,
                'db_table': 'kset',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('keyphrase', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('keyphrases', models.TextField()),
            ],
            options={
                'managed': False,
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='T',
            fields=[
                ('keyphrase_parent', models.CharField(db_column='keyphraseParent', max_length=255, primary_key=True, serialize=False)),
                ('keyphrases_child', models.CharField(db_column='keyphrasesChild', max_length=255)),
                ('name', models.TextField(db_column='name')),
                ('t_index', models.CharField(max_length=255)),
                ('t_order', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'T',
            },
        ),
    ]
